[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
op_sepolia = "https://sepolia.optimism.io"
base = "https://mainnet.base.org"
arbitrum = "https://arb1.arbitrum.io/rpc"
optimism = "https://mainnet.optimism.io"

[etherscan]
base = {key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api"}
arbitrum = {key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
optimism = {key = "${OPSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api"}
base_sepolia = {key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api"}
arbitrum_sepolia = {key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}
op_sepolia = {key = "${OPSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api"}
